let editId=null;
const $=x=>document.getElementById(x);
const msg=x=>{let t=$("toast");t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const amountApplicable=t=>t==="Cashin"||t==="Cashout";
const fmt=v=>v===""||v==null?"—":Number(v).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
function toggleAmount(){let on=amountApplicable($("logType").value);$("amountField").classList.toggle("hidden",!on);$("amount").required=on;if(!on)$("amount").value=""}
function updateStatus(){let n=SheetsSync.queue().length,c=!!SheetsSync.getUrl();$("syncStatus").textContent=c?(n?n+" pending":"Synced"):"Local only";$("syncDetails").textContent=c?(n?n+" pending sync":"Two-way sync enabled"):"Settings hidden"}
function render(){
 let a=LogStore.getAll().filter(x=>!x.deleted),q=($("searchInput").value||"").toLowerCase();
 let f=a.filter(x=>(x.description+" "+x.logType+" "+x.status+" "+(x.userName||"")).toLowerCase().includes(q));
 $("logTableBody").innerHTML=f.map(x=>`<tr><td>${new Date(x.timestamp).toLocaleString("en-IN")}</td><td class="user-cell">${esc(x.userName||"Unknown")}</td><td>${esc(x.logType)}</td><td>${esc(x.description)}</td><td class="amount-cell">${amountApplicable(x.logType)?fmt(x.amount):"—"}</td><td>${esc(x.status)}</td><td><button data-e="${x.id}">Edit</button><button data-d="${x.id}">Delete</button></td></tr>`).join("");
 $("emptyState").style.display=f.length?"none":"block";
 let c={"Total Logs":a.length,"Cashin":0,"Cashin Amount":0,"Cashout":0,"Cashout Amount":0,"Distributor Visits":0,"Customer Feedback":0,"Payment Pending":0,"Ordered":0,"Inventory Added":0};
 a.forEach(x=>{if(x.logType==="Cashin"){c.Cashin++;c["Cashin Amount"]+=Number(x.amount)||0}if(x.logType==="Cashout"){c.Cashout++;c["Cashout Amount"]+=Number(x.amount)||0}if(x.logType==="Distributor visit")c["Distributor Visits"]++;if(x.logType==="Cust. Feedback")c["Customer Feedback"]++;if(x.status==="Payment pending")c["Payment Pending"]++;if(x.status==="Ordered")c.Ordered++;if(x.status==="Inventory added")c["Inventory Added"]++});
 $("statsGrid").innerHTML=Object.entries(c).map(([k,v])=>`<div class="stat"><div>${k}</div><b>${k.endsWith("Amount")?"₹"+fmt(v):v}</b></div>`).join("");updateStatus()
}
async function sync(){if(!Auth.isLoggedIn()||!SheetsSync.getUrl())return;try{await SheetsSync.sync();render();msg("Google Sheets synced")}catch(e){msg("Sync failed; local data kept");updateStatus()}}
function reset(){editId=null;$("logForm").reset();$("logType").value="Log";$("status").value="NA";$("saveBtn").textContent="Add Log";$("cancelEditBtn").classList.add("hidden");toggleAmount()}
$("logType").onchange=toggleAmount;
$("logForm").onsubmit=e=>{e.preventDefault();let old=editId?LogStore.getAll().find(y=>y.id===editId):null,user=Auth.getUser()||{},type=$("logType").value,amount=amountApplicable(type)?Number($("amount").value):null;if(amountApplicable(type)&&(!Number.isFinite(amount)||amount<0)){msg("Enter a valid amount");return}let x={id:editId||crypto.randomUUID(),timestamp:old?old.timestamp:new Date().toISOString(),logType:type,description:$("description").value.trim(),amount,status:$("status").value,userName:old?.userName||user.name||user.email||"Unknown",updatedAt:new Date().toISOString(),updatedBy:user.email||""};if(!x.description)return;LogStore.upsert(x);SheetsSync.enqueue(x);reset();render();sync()};
$("logTableBody").onclick=e=>{let id=e.target.dataset.e||e.target.dataset.d;if(!id)return;let x=LogStore.getAll().find(y=>y.id===id);if(e.target.dataset.e){editId=id;$("logType").value=x.logType;$("description").value=x.description;$("amount").value=x.amount??"";$("status").value=x.status;$("saveBtn").textContent="Update Log";$("cancelEditBtn").classList.remove("hidden");toggleAmount()}else{x.deleted=true;x.updatedAt=new Date().toISOString();x.updatedBy=Auth.getUser()?.email||"";SheetsSync.enqueue(x);LogStore.upsert(x);render();sync()}};
$("cancelEditBtn").onclick=reset;$("searchInput").oninput=render;$("clearAllBtn").onclick=()=>{if(confirm("Delete local data?")){LogStore.clear();render()}};$("toggleSync").onclick=()=>{$("syncPanel").classList.toggle("hidden");$("toggleSync").textContent=$("syncPanel").classList.contains("hidden")?"Show Sync Settings":"Hide Sync Settings"};$("sheetUrl").value=SheetsSync.getUrl();$("saveSheetUrl").onclick=()=>{SheetsSync.setUrl($("sheetUrl").value);render();sync()};$("syncNow").onclick=sync;addEventListener("online",sync);
function authUI(){let ok=Auth.isLoggedIn();$("loginCard").classList.toggle("hidden",ok);$("appContent").classList.toggle("hidden",!ok);$("loginBtn").classList.toggle("hidden",ok);$("logoutBtn").classList.toggle("hidden",!ok);$("userSubtitle").textContent=ok?"Signed in: "+Auth.getUser().email:"Activity & cash log";render()}$("logoutBtn").onclick=()=>{Auth.clear();authUI();msg("Logged out")};$("loginBtn").onclick=()=>$("loginCard").scrollIntoView({behavior:"smooth"});window.onGoogleCredential=token=>{let p=JSON.parse(atob(token.split(".")[1].replace(/-/g,"+").replace(/_/g,"/")));Auth.save({email:p.email,name:p.name||p.email,idToken:token});authUI();sync()};window.addEventListener("load",()=>{Auth.load();authUI();if(window.google){google.accounts.id.initialize({client_id:"99773349762-ok4gijm3iedsqu7alk1k61vur86n7v3j.apps.googleusercontent.com",callback:r=>window.onGoogleCredential(r.credential)});google.accounts.id.renderButton($("googleButton"),{theme:"outline",size:"large"})}});render();