const SHEET="Logs",HEAD=["ID","Timestamp","Date","Time","Log Type","Description","Status","Synced At","Updated At","Updated By","Deleted"];
function doGet(){return out({ok:true,version:"3.0"})}
function doPost(e){try{let b=JSON.parse(e.postData.contents||"{}"),email=String(b.user?.email||"").toLowerCase().trim();if(!email||!allowed(email))throw Error("Unauthorized Google account");let s=getSheet(),h=headers(s),m=map(h),incoming={};(b.logs?.localLogs||[]).concat(b.logs?.pendingLogs||[]).forEach(x=>{if(x?.id)incoming[String(x.id)]=x});let rem=records(s,h,m);Object.keys(incoming).forEach(id=>{let x=incoming[id];if(!rem[id])append(s,h,m,x,email);else if(new Date(x.updatedAt||x.timestamp).getTime()>new Date(rem[id].updatedAt||rem[id].timestamp).getTime())update(s,rem[id].row,h,m,x,email)});rem=records(s,h,m);return out({ok:true,logs:Object.values(rem).map(x=>toLog(x,h,m))})}catch(e){return out({ok:false,error:String(e.message||e)})}}
function allowed(e){return (PropertiesService.getScriptProperties().getProperty("ALLOWED_EMAILS")||"").split(",").map(x=>x.trim().toLowerCase()).includes(e)}
function getSheet(){let s=SpreadsheetApp.getActive().getSheetByName(SHEET);if(!s)s=SpreadsheetApp.getActive().insertSheet(SHEET);let h=headers(s);let have=h.map(norm);HEAD.forEach(x=>{if(!have.includes(norm(x)))s.getRange(1,s.getLastColumn()+1).setValue(x)});return s}
function headers(s){return s.getLastColumn()?s.getRange(1,1,1,s.getLastColumn()).getValues()[0].map(String):[]}
function map(h){let m={};h.forEach((x,i)=>m[norm(x)]=i);return m}
function records(s,h,m){let o={};if(s.getLastRow()<2)return o;s.getRange(2,1,s.getLastRow()-1,h.length).getValues().forEach((r,i)=>{let id=String(val(r,m,"ID")||"");if(id)o[id]={row:i+2,id,updatedAt:String(val(r,m,"Updated At")||val(r,m,"Timestamp")||""),timestamp:String(val(r,m,"Timestamp")||""),values:r}});return o}
function append(s,h,m,x,e){let r=new Array(h.length).fill("");fill(r,m,x,e);s.getRange(s.getLastRow()+1,1,1,h.length).setValues([r])}
function update(s,n,h,m,x,e){let r=s.getRange(n,1,1,h.length).getValues()[0];fill(r,m,x,e);s.getRange(n,1,1,h.length).setValues([r])}
function fill(r,m,x,e){put(r,m,"ID",x.id);put(r,m,"Timestamp",x.timestamp||new Date().toISOString());let d=new Date(x.timestamp||new Date());put(r,m,"Date",Utilities.formatDate(d,Session.getScriptTimeZone(),"yyyy-MM-dd"));put(r,m,"Time",Utilities.formatDate(d,Session.getScriptTimeZone(),"HH:mm:ss"));put(r,m,"Log Type",x.logType||"");put(r,m,"Description",x.description||"");put(r,m,"Status",x.status||"");put(r,m,"Synced At",new Date());put(r,m,"Updated At",x.updatedAt||new Date().toISOString());put(r,m,"Updated By",e);put(r,m,"Deleted",!!x.deleted);Object.keys(x).forEach(k=>{if(!["id","timestamp","logType","description","status"].includes(k))put(r,m,k,x[k])})}
function toLog(x,h,m){return{id:x.id,timestamp:x.timestamp,logType:String(val(x.values,m,"Log Type")||""),description:String(val(x.values,m,"Description")||""),status:String(val(x.values,m,"Status")||""),updatedAt:x.updatedAt,deleted:Boolean(val(x.values,m,"Deleted")||false)}}
function val(r,m,k){let i=m[norm(k)];return i===undefined?"":r[i]}function put(r,m,k,v){let i=m[norm(k)];if(i!==undefined)r[i]=v}function norm(x){return String(x||"").trim().toLowerCase().replace(/[_-]+/g," ").replace(/\s+/g," ")}function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}